### PR TITLE
Added 'range' as builtin function

### PR DESCRIPTION
**Pull request by shivamtrivedi01**

### CODE REVIEW

**Comment by zeroSteiner** [comment]
Thanks a lot, this looks pretty cool. I'll try and review and test it more thoroughly this weekend.

**Review by zeroSteiner — CHANGES_REQUESTED** [review]
The code and tests all look great. I left just one comment and have an additional request: would you mind please adding the function to the docs? It would go here in this section: https://github.com/zeroSteiner/rule-engine/blob/master/docs/source/syntax.rst#functions

Thanks!

**Comment by shivamtrivedi01** [comment]
@zeroSteiner Changes done. Thanks for the review!

**Comment by zeroSteiner** [comment]
Thank you very much for your contribution. This will be included in the 4.4.0 release. I'll probably wait a week before that release is finalized to consider any other changes.

**Comment by zeroSteiner** [comment]
This took me longer than a week but the 4.4.0 version which includes this change is now released and has been [posted to PyPi](https://pypi.org/project/rule-engine/4.4.0/). Thank you very much for your contribution!

**Pull request merged**
